// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Opdracht_Web_API.Data;

namespace Opdracht_Web_API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210413094217_remove-orders-add-categories")]
    partial class removeordersaddcategories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Opdracht_Web_API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lamps"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cleaning"
                        });
                });

            modelBuilder.Entity("Opdracht_Web_API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("AmountInStock")
                        .HasColumnType("int");

                    b.Property<double>("BuyPrice")
                        .HasColumnType("float");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaxLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TaxLevelId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            AmountInStock = 100,
                            BuyPrice = 2.0,
                            CategoryId = 1,
                            Code = "L0001",
                            Name = "Lamp",
                            TaxLevelId = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            AmountInStock = 35,
                            BuyPrice = 20.0,
                            CategoryId = 2,
                            Code = "E0001",
                            Name = "Toaster",
                            TaxLevelId = 1
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            AmountInStock = 10,
                            BuyPrice = 150.0,
                            CategoryId = 2,
                            Code = "E0002",
                            Name = "Refrigerator",
                            TaxLevelId = 1
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            AmountInStock = 10,
                            BuyPrice = 200.0,
                            CategoryId = 3,
                            Code = "E0003",
                            Name = "Washing machine",
                            TaxLevelId = 1
                        },
                        new
                        {
                            Id = 5,
                            Active = false,
                            AmountInStock = 10,
                            BuyPrice = 200.0,
                            CategoryId = 3,
                            Code = "E0004",
                            Name = "Dishwasher",
                            TaxLevelId = 1
                        },
                        new
                        {
                            Id = 6,
                            Active = false,
                            AmountInStock = 30,
                            BuyPrice = 15.0,
                            CategoryId = 2,
                            Code = "E0005",
                            Name = "Mixer",
                            TaxLevelId = 1
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            AmountInStock = 40,
                            BuyPrice = 100.0,
                            CategoryId = 3,
                            Code = "E0006",
                            Name = "Iron",
                            TaxLevelId = 1
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            AmountInStock = 20,
                            BuyPrice = 20.0,
                            CategoryId = 3,
                            Code = "H0001",
                            Name = "Ironing board",
                            TaxLevelId = 1
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            AmountInStock = 25,
                            BuyPrice = 250.0,
                            CategoryId = 2,
                            Code = "E0007",
                            Name = "Food processor",
                            TaxLevelId = 1
                        });
                });

            modelBuilder.Entity("Opdracht_Web_API.Models.Tax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaxPercentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Taxes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "standard",
                            TaxPercentage = 21
                        },
                        new
                        {
                            Id = 2,
                            Name = "exceptions and meals",
                            TaxPercentage = 12
                        },
                        new
                        {
                            Id = 3,
                            Name = "basic",
                            TaxPercentage = 6
                        });
                });

            modelBuilder.Entity("Opdracht_Web_API.Models.Product", b =>
                {
                    b.HasOne("Opdracht_Web_API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opdracht_Web_API.Models.Tax", "TaxLevel")
                        .WithMany("Products")
                        .HasForeignKey("TaxLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("TaxLevel");
                });

            modelBuilder.Entity("Opdracht_Web_API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Opdracht_Web_API.Models.Tax", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
